/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthRouteImport } from './routes/oauth'
import { Route as ApiRedgifsIdRouteImport } from './routes/api/redgifs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthRoute = OauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRedgifsIdRoute = ApiRedgifsIdRouteImport.update({
  id: '/api/redgifs/$id',
  path: '/api/redgifs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oauth': typeof OauthRoute
  '/api/redgifs/$id': typeof ApiRedgifsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oauth': typeof OauthRoute
  '/api/redgifs/$id': typeof ApiRedgifsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oauth': typeof OauthRoute
  '/api/redgifs/$id': typeof ApiRedgifsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/oauth' | '/api/redgifs/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/oauth' | '/api/redgifs/$id'
  id: '__root__' | '/' | '/oauth' | '/api/redgifs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OauthRoute: typeof OauthRoute
  ApiRedgifsIdRoute: typeof ApiRedgifsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth': {
      id: '/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof OauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/redgifs/$id': {
      id: '/api/redgifs/$id'
      path: '/api/redgifs/$id'
      fullPath: '/api/redgifs/$id'
      preLoaderRoute: typeof ApiRedgifsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OauthRoute: OauthRoute,
  ApiRedgifsIdRoute: ApiRedgifsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
